# --- KONFIGURASI DATABASE LOKAL (XAMPP) ---
# Menggunakan driver MySQL terbaru
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Mengarahkan ke database 'simple_blog' di localhost port 3306
spring.datasource.url=jdbc:mysql://localhost:3306/simple_blog?useSSL=false&serverTimezone=UTC

# Username default XAMPP adalah root
spring.datasource.username=root

# Password default XAMPP dibiarkan kosong
spring.datasource.password=

# --- KONFIGURASI HIBERNATE / JPA ---
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=false

# TAMBAHAN SANGAT PENTING: Perintah agar tabel otomatis dibuat di phpMyAdmin
spring.jpa.hibernate.ddl-auto=update

spring.freemarker.suffix=.ftl